version: "3.8"

services:
  cineboard:
    image: sinscum/cineboard:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      TZ: "Australia/Brisbane"
      BASEPATH: ""
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    restart: unless-stopped


