version: "3.8"

services:
  cineboard:
    image: ghcr.io/sinscum/cineboard:latest
    container_name: cineboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "Australia/Brisbane"
      NODE_ENV: production
      BASEPATH: ""
      ET: "false"
    volumes:
      - ./docker/CineBoard/custom:/usr/src/app/public/custom
      - ./docker/CineBoard/config:/usr/src/app/config
    ports:
      - "9876:3000"
    restart: unless-stopped

